### ISSUE TITLE
Update settings inputs

### ISSUE THREAD

**Issue by NickGreen** [a8cteam51/feedland-blogroll#8]
### Synopsis

In an effort to simplify the settings, we will split the settings that determine the feed into 3 easier-to-understand inputs.

### Details

Remove these two inputs:
- Blogroll OPML URL
- Feedland View Blogroll URL

Add 3 new inputs:
- Username 
(required. davewiner default) (maybe a tooltip that says "Username associated with the FeedLand feed you want to display on your site.")
- Category 
(optional. blogroll default) 
- Server 
(required. https://feedland.com default)

Then, on the plugin side, we can use the 3 new inputs to construct the the two values that we are passing to the feedland scripts:
```
'feedland_blogroll_urlBlogrollOpml'         => 'https://feedland.social/opml?screenname=davewiner&catname=blogroll',
'feedland_blogroll_urlFeedlandViewBlogroll' => 'https://feedland.social/?username=davewiner&catname=blogroll',
```

No changes should be needed of the feedland scripts for this change.

**Comment by scripting** [comment]
A couple of problems --  

1. The category should default to the empty string. You can form the OPML url without a category easily enough, see the next comment for an example.
2. We are not as far as I know setting the value for _urlSocketServer_ which defaults to `wss://feedland.social/`. This won't result in an error, but there's no guarantee that feedland.social knows anything about the feeds you're using. This value has to be set based on what they enter for server. If it's feedland.com, the resulting value will be the url of the socket server for feedland.com which is `wss://feedland.com:443/_ws/`

**Comment by scripting** [comment]
If the user leaves the category empty, this would be the URL of their OPML feed.

https://feedland.com/opml?screenname=davewiner

**Comment by fmfernandes** [comment]
@scripting, there's two URLs:

- BlogrollOpml: https://feedland.social/opml?screenname=davewiner&catname=blogroll
- FeedlandViewBlogroll: https://feedland.social/?username=davewiner&catname=blogroll

The first one without a category is https://feedland.social/opml?screenname=davewiner but what about the second one? Can we use https://feedland.social/?username=davewiner?

**Comment by scripting** [comment]
I could set the default for urlSocketServer to the one for feedland.com and push this issue off to the future. i think that's the best way to deal with it. I'll think about it for an hour or two, @NickGreen -- let me know what you think about this way of dealing with it.

Also be aware we're setting it up so there's some amount of lock-in: people using this plugin and it's current way of configuring will only be able to use it with FeedLand. It wouldn't be able to work with any of our competitors, who don't exist at this time, but that's not an acceptable reason imho.  

But the plugin is open source, and it wouldn't take a lot of programming depth to be able to set it up to work with another back-end, and even release it for others to use. 

I'm putting this note here now so it's clear we were thinking about this, and also providing a workaround for the lockin. ;-)

**Comment by scripting** [comment]
@fmfernandes -- 

The second one is used for this command:

![image](https://github.com/a8cteam51/feedland-blogroll/assets/1686843/46c8aa6d-4602-4baa-8de7-609cb64c1e46)

It would take me to:

https://feedland.com/?username=davewiner

So yes, you got it right.

**Comment by scripting** [comment]
Which btw, nullifies the bit about lockin. This product is obviously designed to hook up to FeedLand. I'm juggling so much stuff now I forget how I thought this through when I was developing it.

**Comment by NickGreen** [comment]
@scripting If I understand your suggestion correctly, is the idea that we could remove the "server" input from the settings page, and just have it always use Feedland.com as the server? 

I think this is a fair thing to do. If people ask for it, we could always expose that setting later on. But until then, it seems like a good simplification, IMO.

**Comment by scripting** [comment]
@NickGreen -- that wasn't what I was thinking, but it's totally appropriate.  go for it. ;-)

**Comment by fmfernandes** [comment]
Updated settings page accordingly on #9 and tagged a new release: https://github.com/a8cteam51/feedland-blogroll/releases/tag/1.1.0
